blank_issues_enabled: true
contact_links:
  - name: Contact Code Calories
    url: https://codecalories.com/connect
    about: Connect With Us.
  - name: How To Make A Question
    url: https://codecalories.com/guide
    about: Guidline.
