name: New Exercise
description: File an exercise
title: "[New Exercise]: EXERCISE_TITLE_HERE"
labels: ["exercise"]
assignees:
  - codecalories
body:
  - type: textarea
    id: Summary
    attributes:
      label: Summary
      description: Summary of your exercise.
      placeholder: Summary Here      
    validations:
      required: true
  
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: Description of exercise.
      placeholder: Description
    validations:
      required: true
      
  - type: dropdown
    id: language
    attributes:
      label: Language
      description: What language is your exercise about?
      options:
        - Python
        - Java
        - Java Script
        - C
        - C++
        - C#
        - Other
    validations:
      required: true
      
  - type: input
    id: other-languages
    attributes:
      label: Other Languages
      description: "if you choose other languages or want to write multiple languages write here. (first select 'other')"
      placeholder: "Your language/s here"
    validations:
      required: true  
      
  - type: dropdown
    id: Difficulty-Level
    description: for more information check the [documentation](https://github.com)
    attributes:
      label: Difficulty level 
      multiple: false
      options:
        - 1 (easy)
        - 2
        - 3 (medium)
        - 4
        - 5 (hard)
        
  - type: input
    id: topics
    attributes:
      label: Related Topics
      description: Write the related topics here. for more information check the [documentation](https://github.com)
    validations:
      required: true
      
      
      
      
