name: New Exercise
description: File an exercise
title: "[New Exercise]: EXERCISE_TITLE_HERE"
labels: ["exercise"]
assignees:
  - codecalories
body:
  - type: textarea
    id: Summary
    attributes:
      label: Summary
      description: Summary of the exercise.
      placeholder: Summary Here
    validations:
      required: true
  
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: Description of exercise.
      placeholder: Description
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Language
      description: What language is the exercise about?
      options:
        - Python
        - Java
        - Java Script
        - C
        - C++
        - C#
        - Other
    validations:
      required: true

  - type: input
    id: other-languages
    attributes:
      label: Other Languages
      description: if you choose other languages or want to write multiple languages write here (first select 'other').  [if this should be blank write `_blank_` or `blank`]
      placeholder: "language/s here"
    validations:
      required: true

  - type: dropdown
    id: Difficulty-Level
    attributes:
      label: Difficulty level
      description: for more information check the [documentation](https://github.com)
      multiple: false
      options:
        - 1 (easy)
        - 2
        - 3 (medium)
        - 4
        - 5 (hard)

  - type: input
    id: topics
    attributes:
      label: Related Topics
      description: Write the related topics here. for more information check the [documentation](https://github.com)
    validations:
      required: true

  - type: input
    id: related-technologies
    attributes:
      label: Related Technologies
      description: Write the related technologies here. for more information check the [documentation](https://github.com)
    validations:
      required: true

  - type: input
    id: keywords
    attributes:
      label: Related Keywords
      description: Write the related keywords here. for more information check the [documentation](https://github.com)
    validations:
      required: true

  - type: textarea
    id: Extra-Information
    attributes:
      label: Extra Information
      description: Any Extra Inforamtion 
      placeholder: Description
    validations:
      required: true
      
  - type: input
    id: contact
    attributes:
      label: Contact Details [Email]
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
