name: "Test Issue Label"
on: [issues, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Code-Hex/first-label-interaction@v1.0.1
        with:
          issue-labels: '["exercise", "help wanted"]'
          pr-labels: '["help wanted"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
